#!/bin/bash

rsync -rvz --progress --exclude-from=/home/jason/public_html/gutenberg/wp-content/plugins/alumni-quiz/rsync-exclude.txt ~/public_html/gutenberg/wp-content/plugins/alumni-quiz/ ~/public_html/ucsc-magazine/wp-content/plugins/alumni-quiz/